name: Martina Wicki Photography
favicon: null
layout_spectrum: 0.5517677944153547
typography_spectrum: 0.34531285683624446
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.026130859507247806
  lightness: 0.09354686341248453
  saturation: 0.4680768826510757
  rhythmicContrast: 0.20801416342146695
purpose: []
